# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/edge/all/edge.rbi
#
# edge-0.6.0
module Edge
end
module Edge::Forest
end
module Edge::Forest::ActsAsForest
  def acts_as_forest(options = nil); end
end
module Edge::Forest::ClassMethods
  def cte_sql; end
  def find_forest; end
  def find_tree(id_or_ids); end
  def with_descendants; end
end
module Edge::Forest::InstanceMethods
  def ancestors; end
  def descendants; end
  def root; end
  def root?; end
  def siblings; end
end
class ActiveRecord::Base
  extend Edge::Forest::ActsAsForest
end
