# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jb/all/jb.rbi
#
# jb-0.7.0
module Jb
end
class Jb::Railtie < Rails::Railtie
end
module ActionController
end
module ActionController::ApiRendering
  include ActionView::Rendering
end
module Jb::TemplateRenderer
end
module Jb::TemplateRenderer::JSONizer
  def render_template(_view, template, *arg2); end
end
module Jb::PartialRendererExtension
  def render_collection(_view, template); end
end
class Jb::Handler
  def default_format; end
  def default_format=(val); end
  def default_format?; end
  def self.call(template, source = nil); end
  def self.default_format; end
  def self.default_format=(val); end
  def self.default_format?; end
  def self.handles_encoding?; end
end
