# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-sound/all/minitest-sound.rbi
#
# minitest-sound-0.0.8
module Minitest
end
module Minitest::Sound
  def self.during_test; end
  def self.during_test=(arg0); end
  def self.failure; end
  def self.failure=(arg0); end
  def self.success; end
  def self.success=(arg0); end
end
