# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-slow_test/all/minitest-slow_test.rbi
#
# minitest-slow_test-0.2.0
module Minitest
end
module Minitest::SlowTest
  def self.exclude_test_name; end
  def self.exclude_test_name=(arg0); end
  def self.long_test_time; end
  def self.long_test_time=(arg0); end
end
