# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-sub_test_case/all/minitest-sub_test_case.rbi
#
# minitest-sub_test_case-0.1.2
module Minitest
end
module Minitest::SubTestCase
  def sub_test_case(name, &block); end
end
class Minitest::Test < Minitest::Runnable
  extend Minitest::SubTestCase
end
