# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/models-to-sql-rails/all/models-to-sql-rails.rbi
#
# models-to-sql-rails-23c32025ceb5
class Array
  def to_sql_insert(*anything); end
end
module ModelsToSql
end
module ModelsToSql::ActiveRecord
  def to_sql_insert(options = nil); end
end
class ModelsToSql::Climber
  def self.climb(model, output, baton = nil); end
  def self.sql(model); end
end
class ActiveRecord::Base
  include ModelsToSql::ActiveRecord
end
