language: ruby
sudo: false
rvm:
  - 2.3.0
env:
  - DB=postgresql
bundler_args: "--without production"
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - xvfb-run bundle exec rake test
before_script:
  - export TZ=Asia/Tokyo
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
  - bundle update
  - npm install
cache: bundler
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: IY/9uoCL7nmVCAq64rTw0t9x5hjySFdMJQWWQ43opvV3BOpzM9WlkqxibpCDjRD9en4itMV9OlaQJlGO/q2XwOseQQcQHuJCCUkTt4E9CdI2paaPnZaVT/CL5SD2ZYa3n7omUIPfftM9giOr7qRzr71tH95PuFQ8yw3IBO9rIA8=
  app:
    master: wikin
  on:
    repo: y-yagi/wikin
