language: ruby
sudo: required
rvm:
  - 2.3.1
env:
  - DB=postgresql
bundler_args: "--without production"
cache:
  bundler: true
  directories:
    - $HOME/.yarn-cache
before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
script:
  - RAILS_ENV=test bin/rails db:migrate
  - xvfb-run bin/rails test
before_script:
  - export TZ=Asia/Tokyo
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
  - bundle update
  - yarn install
cache: bundler
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: IY/9uoCL7nmVCAq64rTw0t9x5hjySFdMJQWWQ43opvV3BOpzM9WlkqxibpCDjRD9en4itMV9OlaQJlGO/q2XwOseQQcQHuJCCUkTt4E9CdI2paaPnZaVT/CL5SD2ZYa3n7omUIPfftM9giOr7qRzr71tH95PuFQ8yw3IBO9rIA8=
  app:
    master: wikin
  on:
    repo: y-yagi/wikin
