language: ruby
rvm:
- 2.1.4
env:
- DB=postgresql
bundler_args: "--without development"
cache: bundler
script:
- RAILS_ENV=test bundle exec rake db:migrate
- xvfb-run bundle exec rake test
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database database_test' -U postgres
- echo 'Asia/Tokyo' | sudo tee /etc/timezone
- sudo dpkg-reconfigure --frontend noninteractive tzdata
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: IY/9uoCL7nmVCAq64rTw0t9x5hjySFdMJQWWQ43opvV3BOpzM9WlkqxibpCDjRD9en4itMV9OlaQJlGO/q2XwOseQQcQHuJCCUkTt4E9CdI2paaPnZaVT/CL5SD2ZYa3n7omUIPfftM9giOr7qRzr71tH95PuFQ8yw3IBO9rIA8=
  app:
    master: wikin
  on:
    repo: y-yagi/wikin
