# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

development:
  adapter: async

test:
  adapter: async
